kind = "web"
previewPath = "/"
title = "Benkiz Catering Company"
version = "1.0.0"
id = "artifacts/Benkiz-catering"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23141

[services.development]
run = "pnpm --filter @workspace/Benkiz-catering run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/Benkiz-catering", "run", "build" ]
publicDir = "artifacts/Benkiz-catering/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23141"
BASE_PATH = "/"
